spring.application.name=LikeLion hackathon

spring.datasource.url=jdbc:h2:mem:hackathondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=jiu201325
spring.datasource.password=jiu20132025!!
spring.h2.console.enabled=true
mfds.service-key=yb/Cex8zUIPad3Edjrm5Gv7J1Pc3PfQB4NcoQA6R8dueovI6E5Mey1oV7vNfuGqwvnBdM3FJtaoMTVhXJiv3TA==